"""empty message

Revision ID: 06b3427ac51d
Revises: 356ac2a897cc
Create Date: 2024-02-25 20:30:28.946299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b3427ac51d'
down_revision = '356ac2a897cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_user_update', sa.String(length=50), nullable=True))

    with op.batch_alter_table('rhythm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_user_update', sa.String(length=50), nullable=True))

    with op.batch_alter_table('rock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_user_update', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rock', schema=None) as batch_op:
        batch_op.drop_column('latest_user_update')

    with op.batch_alter_table('rhythm', schema=None) as batch_op:
        batch_op.drop_column('latest_user_update')

    with op.batch_alter_table('folk', schema=None) as batch_op:
        batch_op.drop_column('latest_user_update')

    # ### end Alembic commands ###
