"""empty message

Revision ID: b4652126bee8
Revises: 06b3427ac51d
Create Date: 2024-02-26 06:52:27.337996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4652126bee8'
down_revision = '06b3427ac51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folk', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('rhythm', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('rock', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rock', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)

    with op.batch_alter_table('rhythm', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)

    with op.batch_alter_table('folk', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###
